services:
  datalore:
    image: jetbrains/datalore-server:2024.5
    # ports:
    #   - "8080:8080"
    expose: [ "8081", "5050", "4060" ]
    networks:
      - datalore-agents-network
      - datalore-backend-network
      - traefik-public
    volumes:
      - "datalore-storage:/opt/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DATALORE_PUBLIC_URL: "https://ist.rest"
      DB_PASSWORD: ${DB_PASSWORD}
      EMAIL_ALLOWLIST_ENABLED: "true"
      MAIL_SMTP_SERVER: "smtp-relay.brevo.com"
      MAIL_SMTP_PORT: "587"
      MAIL_SENDER_USERNAME: ${MAIL_SENDER_USERNAME}
      MAIL_SENDER_PASSWORD: ${MAIL_SENDER_PASSWORD}
      MAIL_SENDER_EMAIL: "no_reply@ist.rest"
      MAIL_SENDER_NAME: "Datalore TR"
      FORCE_EMAIL_VERIFICATION: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.datalore.entrypoints=websecure
      - traefik.http.routers.datalore.rule=Host(`ist.rest`)
      - traefik.http.services.datalore.loadbalancer.server.port=8080
      - traefik.http.routers.datalore.tls=true
      - traefik.http.routers.datalore.tls.certresolver=le
    
  postgresql:
    image: jetbrains/datalore-postgres:2024.4
    expose: [ "5432" ]
    networks:
      - datalore-backend-network
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgresql-data: { }
  datalore-storage: { }
networks:
  datalore-agents-network:
    name: datalore-agents-network
  datalore-backend-network:
    name: datalore-backend-network
  traefik-public:
    external: true
